agent/src/main/python/views/view_auth.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020-04-08 16:40:20
# @Desc    : 授权配置
# @File    : view_auth.py
from application_config import app
from application_config import login_manager
from bin.assets import compile_auth_assets
from db.model_logging_login import LoginLogging
from db.models import User
from flask import redirect, render_template, flash, Blueprint, url_for
from flask import request
from flask_login import login_user, current_user, logout_user
from form.form_auth import AuthSignin, AuthSignup
from services.service_logging_login import LoginLoggingService
from services.service_user import UserService

auth_view = Blueprint('auth_view', __name__, template_folder='templates', static_folder='static')

compile_auth_assets(app)


@auth_view.route('/signin', methods=['GET', 'POST'])
def signin():
    """
    登录视图
    """
    logging_login = LoginLogging()
    logging_login.ip = request.remote_addr
    if current_user.is_authenticated:
        logging_login.status = True
        logging_login.reason = '用户已登录'
        LoginLoggingService().add(model=logging_login, user_id=current_user.id)
        return redirect(url_for('dashboard_view.index'))
    login_form = AuthSignin()
    if request.method == 'POST':
        if login_form.validate_on_submit():
            email = login_form.email.data
            password = login_form.password.data
            user = UserService().find_by_email(email=email)
            if user and user.check_password(password=password):
                login_user(user)
                UserService().update_last_login_time(user)
                next_page = request.args.get('next')
                logging_login.status = True
                LoginLoggingService().add(model=logging_login, user_id=current_user.id)
                return redirect(next_page or url_for('dashboard_view.index'))
        flash('输入的密码错误')
        logging_login.status = False
        logging_login.reason = '输入的密码错误'
        LoginLoggingService().add(model=logging_login, user_id=user.id)
        return redirect(url_for('auth_view.signin'))
    return render_template('auth/signin.html', form=login_form, title='用户登录')


@auth_view.route('/sign_out')
def logout():
    logout_user()
    flash(u'当前用户已经退出登录')
    return redirect(url_for('auth_view.signin'))


@auth_view.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    用户注册
    GET: 注册页面
    POST: 如果提交的凭证有效，将用户重定向到登录的主页
    """
    signup_form = AuthSignup()
    if request.method == 'POST':
        if signup_form.validate_on_submit():
            name = signup_form.name.data
            email = signup_form.email.data
            password = signup_form.password.data
            confirm_password = signup_form.confirm_password.data
            existing_user = UserService().find_by_email(email=email)
            if existing_user is None:
                user = User(name=name, email=email, password=password)
                if UserService().add(user=user):
                    login_user(user)
                    return redirect(url_for('dashboard_view.index'), code=400)
            flash('该电子邮件地址已经被注册')
            return redirect(url_for('auth_view.signup'))
    return render_template('auth/signup.html', title='注册账号', form=signup_form)


@login_manager.user_loader
def load_user(user_id):
    """
    检查用户是否登录
    :param user_id: 用户ID
    :return: 登录状态
    """
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """
    将未经授权的用户重定向到503界面
    :return: 重定向
    """
    flash('您没有权限访问当前页面，请登录。')
    return redirect(url_for('auth_view.signin'))

agent/src/main/python/templates/base.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "bootstrap/base.html" %}
{% block title %}iMonitor - {% endblock %}
{% block head %}
{% block page_styles %}{% endblock %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
<link href="https://cdn.bootcss.com/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
<link href="{{ url_for('static', filename = 'style.css') }}" rel="stylesheet">
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>

{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">iMonitor</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/">主页 <span class="sr-only">(current)</span></a>
                </li>
                {% if current_user and current_user.is_authenticated %}
                <li class="{% if active_menu == 'dashboard' %} active {% endif %}">
                    <a href="{{ url_for('dashboard_view.index') }}">仪表盘</a>
                </li>
                <li class="{% if active_menu == 'host' %} active {% endif %}">
                    <a href="{{ url_for('host_view.index') }}">主机管理</a>
                </li>
                {% endif %}
                <!--                <li class="dropdown">-->
                <!--                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"-->
                <!--                       aria-expanded="false">其他 <span class="caret"></span></a>-->
                <!--                    <ul class="dropdown-menu">-->
                <!--                        <li><a href="/d">404</a></li>-->
                <!--                    </ul>-->
                <!--                </li>-->
            </ul>
            <!--<form class="navbar-form navbar-left">-->
            <!--<div class="form-group">-->
            <!--<input type="text" class="form-control" placeholder="Search">-->
            <!--</div>-->
            <!--<button type="submit" class="btn btn-default">Submit</button>-->
            <!--</form>-->
            {% if current_user and current_user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <img src="{{ url_for('static', filename = 'imgs/avatar/' + current_user.avatar) }}"
                             alt="{{current_user.name}}" class="img-circle avatar-w20"/>
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ url_for('settings_view.profile') }}">
                                <span class="fa-stack">
                                    <i class="fas fa-square fa-stack-2x"></i>
                                    <i class="fas fa fa-cog fa-stack-1x fa-inverse"></i>
                                </span> 设置
                            </a></li>
                        <li>
                            <a href="{{ url_for('auth_view.logout') }}">
                                <span class="fa-stack">
                                    <i class="fas fa-square fa-stack-2x"></i>
                                    <i class="fas fa fa-sign-out-alt fa-stack-1x fa-inverse"></i>
                                </span> 退出
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <div class="nav navbar-nav navbar-right">
                <a type="button" class="btn btn-default navbar-btn btn-sm" href="/auth/signin">登 录</a>
                <a type="button" class="btn btn-default navbar-btn btn-sm btn-info" href="/auth/signup">注 册</a>
            </div>
            {% endif %}
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

{{ moment.include_moment(local_js="https://cdn.bootcss.com/moment.js/2.22.1/moment.min.js") }}

{% endblock %}

agent/src/main/python/templates/host.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}主机管理{% endblock %}

{% block page_content %}
<div class="page-header">
    {% if name %}
    <h1>Hello, {{ name }}!</h1>
    {% else %}
    <h1>Hello,Stranger!</h1>
    {% endif %}
</div>
{{ wtf.quick_form(form) }}

{#<p>{{ moment(current_time).format('LLL') }}</p>#}
{#<p>{{ moment(current_time).fromNow(refresh=True) }}</p>#}

{% endblock %}

agent/src/main/python/templates/index.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}首页{% endblock %}

{% block page_content %}
<!-- 监控数据 -->
<div class="card mt10">
    <h5 class="card-header">
        <button class="btn btn-sm btn-primary right" type="button">刷新</button>
    </h5>
    <div class="card-body">
        <table class="table">
            <thead>
            <tr>
                <th>名称</th>
                <th>状态</th>
                <th>启动用户</th>
                <th>上报时间</th>
                <th>进程ID</th>
                <th>主机地址</th>
                <th>错误编码</th>
                <th>错误信息</th>
                <th>节点操作</th>
            </tr>
            </thead>
            <!-- 监控数据信息 -->
            <tbody>
            {% for heartbeat in heartbeats %}
            <tr class="{% if heartbeat.service_status == 'DOWN' %}down_background{% endif %}">
                <td>{{heartbeat['service_name']}}</td>
                <td>
                    <i class="fa {% if heartbeat.service_status == 'UP' %}fa-thumbs-up up {% else %}fa-thumbs-down down{% endif %}"
                       data-toggle="tooltip" data-placement="top"
                       title="{% if heartbeat.service_status == 'UP' %}当前服务运行正常{% else %}当前服务已宕机{% endif %}"></i>
                </td>
                <td>{{heartbeat['service_username']}}</td>
                <td>{{heartbeat['service_timestamp']}}</td>
                <td>{{heartbeat['service_pid']}}</td>
                <td>{{heartbeat['service_host']}}</td>
                <td>{{heartbeat['service_code']}}</td>
                <td>
                    {% if heartbeat.service_message %}
                    <i class="fa fa-exclamation-triangle" data-toggle="tooltip" data-placement="top"
                       title="{{heartbeat['service_message']}}"></i>
                    {% endif %}
                </td>
                <td>
                    <i class="fa {% if heartbeat.service_status == 'UP' %}fa-stop down{% else %}fa-play up{% endif %}"
                       data-toggle="tooltip" data-placement="top"
                       title="{% if heartbeat.service_status == 'UP' %}下线节点{% else %}启动服务{% endif %}"></i>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{#<p>{{ moment(current_time).format('LLL') }}</p>#}
{#<p>{{ moment(current_time).fromNow(refresh=True) }}</p>#}

{% endblock %}

agent/src/main/python/templates/user.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "base.html" %}
{% block title %} User {% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>Hello, {{ name }}!</h1>
</div>
{% endblock %}