agent/src/main/python/views/view_settings.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020-04-17 00:03:03
# @Desc    : 用户设置脚本
# @File    : view_settings.py
import os
import time
from application_config import logger, codes
from db.models import User
from flask import render_template, request, Blueprint, flash, redirect, url_for
from flask_login import login_required, current_user
from form.form_settings import SettingsProfileForm, BuildModelToFrom, SettingsSecurityForm, SettingsAvatarForm
from services.service_logging_login import LoginLoggingService
from services.service_user import UserService

logger_type = 'settings_view'

settings_view = Blueprint('settings_view', __name__, template_folder='templates')


@settings_view.route('/profile', methods=['GET', 'POST'])
@settings_view.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
def profile(user_id=int):
    form_profile = SettingsProfileForm()
    form_avatar = SettingsAvatarForm()
    user = UserService().find_one(id=current_user.id)
    if form_avatar.validate_on_submit():
        avatar = request.files['avatar']
        path = '{}/{}'.format(codes['config']['avatar'], current_user.id)
        if not os.path.exists(path):
            os.makedirs(path)
        avatar_path = os.path.join(codes['config']['avatar'], '{}/{}.png'.format(current_user.id, int(time.time())))
        avatar.save(avatar_path)
        user.avatar = '{}/{}.png'.format(current_user.id, int(time.time()))
        if UserService().update_avatar(user=user):
            flash('数据更新成功！')
        return redirect(url_for('settings_view.profile', alert_type='success'))
    BuildModelToFrom(user, form_profile)
    if form_profile.validate_on_submit():
        user = User()
        user.id = current_user.id
        user.name = request.form.get('username')
        user.website = request.form.get('website')
        user.position = request.form.get('position')
        user.description = request.form.get('description')
        user.email = request.form.get('email')
        if request.method == 'POST':
            logger.info('execute update operation type <%s> primary key <%s>', logger_type, user.id)
            if UserService().update_one(user=user):
                flash('数据更新成功！')
                return redirect(url_for('settings_view.profile', alert_type='success'))
    if request.args.get('alert_type') is None:
        alter_type = 'danger'
    else:
        alter_type = request.args.get('alert_type')
    return render_template('settings/settings-profile.html', user_id=user_id, title='个人资料', form_profile=form_profile,
                           active_menu='profile', user=user, alert_type=alter_type, avatar_form=form_avatar)

@settings_view.route('/security', methods=['GET', 'POST'])
@login_required
def security():
    form = SettingsSecurityForm()
    if form.validate_on_submit():
        old_password = request.form.get('old_password')
        password = request.form.get('password')
        if current_user.check_password(old_password):
            current_user.password = password
            if UserService().update_password(user=current_user):
                flash('密码更新成功！')
                return redirect(url_for('settings_view.security', alert_type='success'))
        else:
            flash('原密码输入错误')
            return redirect(url_for('settings_view.security'))
    if request.args.get('alert_type') is None:
        alter_type = 'danger'
    else:
        alter_type = request.args.get('alert_type')
    return render_template('settings/settings-security.html', title='安全设置', active_menu='security', form=form,
                           alert_type=alter_type)


@settings_view.route('/logging_login', methods=['GET'])
@login_required
def logging_login():
    loggings = LoginLoggingService().find_all_order_by_user_and_login_time_desc(current_user.id)
    return render_template('settings/settings-logging-login.html', title='登录日志', active_menu='logging-login',
                           loggings=loggings)

agent/src/main/python/templates/settings/base.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %} {{title}} {% endblock %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
{% endblock %}

{% block page_content %}
<div class="row">

    <!-- 提示信息开始 -->
    {% block alert %} {% endblock %}
    <!-- 提示信息结束 -->

    <!-- 个人信息左侧菜单开始 -->
    <div class="col-lg-2 col-12 side-main offset">
        {% block settings_left_menu %}
        <div class="panel panel-default">
            <div class="panel-heading">个人设置</div>
            <div class="panel-body" style="padding: 0px;">
                <div class="list-group" style="margin-bottom: 0px;">
                    <a href="{{ url_for('settings_view.profile') }}"
                       class="list-group-item {% if active_menu == 'profile' %} active {% endif %}">资料</a>
                    <a href="{{ url_for('settings_view.security') }}"
                       class="list-group-item {% if active_menu == 'security' %} active {% endif %}">安全</a>
                    <a href="{{ url_for('settings_view.logging_login') }}"
                       class="list-group-item {% if active_menu == 'logging-login' %} active {% endif %}">登录日志</a>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>
    <!-- 个人信息左侧菜单结束 -->

    <!-- 个人信息右侧数据开始 -->
    <div class="col-lg-10 col-12 conternt-main">
        {% block settings_right_content %} {% endblock %}
    </div>
    <!-- 个人信息右侧数据结束 -->

</div>
{% endblock %}

agent/src/main/python/templates/settings/settings-logging-login.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "settings/base.html" %}

{% block alert %}
{% for message in get_flashed_messages() %}
<div class="alert alert-{{alert_type}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

{% block settings_right_content %}
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">登录日志</div>
    <div class="panel-body">
        <div class="col-lg-9 col-12 conternt-main offset">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>登录时间</th>
                    <th>登录IP</th>
                    <th>登录状态</th>
                </tr>
                </thead>
                <tbody>
                {% for logging in loggings %}
                <tr>
                    <th scope="row">{{ logging.id }}</th>
                    <td>{{ logging.login_time }}</td>
                    <td>{{ logging.ip }}</td>
                    {% if logging.status %}
                    <td>登录成功</td>
                    {% else %}
                    <td class="danger">
                        <span data-toggle="tooltip" data-placement="top" title="{{ logging.reason }}">登录失败 <i
                                class="fas fa-exclamation-triangle"></i></span>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
{% endblock %}

agent/src/main/python/templates/settings/settings-profile.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "settings/base.html" %}

{% block alert %}
{% for message in get_flashed_messages() %}
<div class="alert alert-{{alert_type}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

{% block settings_right_content %}
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">个人资料</div>
    <div class="panel-body">
        <div class="col-lg-9 col-12 conternt-main offset">
            <form method="POST">

                {{ form_profile.csrf_token }}

                <div class="form-group {% if form_profile.username.errors %} has-error {% endif %}">
                    {{ form_profile.username.label(class='control-label') }}
                    {{ form_profile.username(class='form-control') }}
                    {% if form_profile.username.errors %}
                    <ul class="errors">
                        {% for error in form_profile.username.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group {% if form_profile.email.errors %} has-error {% endif %}">
                    {{ form_profile.email.label(class='control-label') }}
                    {{ form_profile.email(class='form-control', disabled="disabled") }}
                    {% if form_profile.email.errors %}
                    <ul class="errors">
                        {% for error in form_profile.email.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group {% if form_profile.description.errors %} has-error {% endif %}">
                    {{ form_profile.description.label(class='control-label') }}
                    {{ form_profile.description(class='form-control') }}
                    {% if form_profile.description.errors %}
                    <ul class="errors">
                        {% for error in form_profile.description.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group {% if form_profile.website.errors %} has-error {% endif %}">
                    {{ form_profile.website.label(class='control-label') }}
                    {{ form_profile.website(class='form-control') }}
                    {% if form_profile.website.errors %}
                    <ul class="errors">
                        {% for error in form_profile.website.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group {% if form_profile.position.errors %} has-error {% endif %}">
                    {{ form_profile.position.label(class='control-label') }}
                    {{ form_profile.position(class='form-control') }}
                    {% if form_profile.position.errors %}
                    <ul class="errors">
                        {% for error in form_profile.position.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form_profile.submit }}
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-12 side-main">
            <div class="bs-example bs-example-images">
                <img class="img-rounded img-w200"
                     src="{% if user.avatar %} {{ url_for('static', filename = 'imgs/avatar/' + user.avatar) }} {% else %} {{ url_for('static', filename = 'imgs/default/avatar.jpg') }} {% endif %}">
                <form method="POST" enctype="multipart/form-data">

                    {{ avatar_form.csrf_token }}

                    <div class="form-group {% if avatar_form.avatar.errors %} has-error {% endif %}">
                        {{ avatar_form.avatar }}
                        {% if avatar_form.avatar.errors %}
                        <ul class="errors">
                            {% for error in avatar_form.avatar.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ avatar_form.submit(class='btn btn-primary btn-xs') }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
{% endblock %}

agent/src/main/python/templates/settings/settings-security.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "settings/base.html" %}

{% block alert %}
{% for message in get_flashed_messages() %}
<div class="alert alert-{{alert_type}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

{% block settings_right_content %}
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">更改密码</div>
    <div class="panel-body">
        <div class="col-lg-9 col-12 conternt-main offset">
            <form method="POST">

                {{ form.csrf_token }}

                <div class="form-group {% if form.old_password.errors %} has-error {% endif %}">
                    {{ form.old_password.label(class='control-label') }}
                    {{ form.old_password(class='form-control') }}
                    {% if form.old_password.errors %}
                    <ul class="errors">
                        {% for error in form.old_password.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                    {{ form.password.label(class='control-label') }}
                    {{ form.password(class='form-control') }}
                    {% if form.password.errors %}
                    <ul class="errors">
                        {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group {% if form.confirm_password.errors %} has-error {% endif %}">
                    {{ form.confirm_password.label(class='control-label') }}
                    {{ form.confirm_password(class='form-control') }}
                    {% if form.confirm_password.errors %}
                    <ul class="errors">
                        {% for error in form.confirm_password.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.submit }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
{% endblock %}