agent/src/main/python/views/view_chart.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020-04-13 18:27:03
# @Desc    : 数据报表脚本
# @File    : view_chart.py
from flask import render_template, Blueprint
from flask_login import login_required

chart_view = Blueprint('chart_view', __name__, template_folder='templates')


@chart_view.route('/host/<int:host_id>/report', methods=['GET'])
@login_required
def report(host_id=int):
    return render_template('chart/chart.html', host_id=host_id, title='主机监控报表')

agent/src/main/python/views/view_host.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020-04-02 23:25:25
# @Desc    : 主机视图脚本
# @File    : view_host.py

from application_config import logger
from common.ssh import Ssh
from common.utils import StringUtils
from db.models import Host
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import current_user
from flask_login import login_required
from form.form_host import HostForm, BuildModelToFrom
from services.service_command_execute import CommandExecuteService
from services.service_host import HostService
from services.service_host_connection import HostConnectionService

host_view = Blueprint('host_view', __name__, template_folder='templates')

logger_type = 'host_view'


@host_view.route('/', methods=['GET'])
@host_view.route('/list', methods=['GET'])
@login_required
def index():
    return render_template('host/host-list.html',
                           hosts=HostService().find_all_order_by_create_time_desc_and_user(current_user),
                           active_menu='host')


@host_view.route('/cmcd/', defaults={'host_id': 0}, methods=['GET', 'POST', 'PUT'])
@host_view.route('/cmcd/<int:host_id>', methods=['GET', 'POST', 'PUT'])
@login_required
def create_modfiy_copy_delete(host_id=int):
    type = request.args.get('type')
    method = request.args.get('method')
    form = HostForm()
    host = HostService().find_one(id=host_id)
    if (host_id <= 0) or host is None:
        title = '新建主机'
    else:
        # 回显表单数据
        BuildModelToFrom(host=host, form=form)
        if (host_id > 0 and type is None):
            title = '修改主机'
        else:
            title = '复制主机'
    if form.validate_on_submit():
        host = Host()
        host.hostname = request.form.get('hostname')
        host.active = True
        host.username = request.form.get('username')
        host.password = request.form.get('security_password')
        host.command = request.form.get('command')
        host.command_start = request.form.get('command_start')
        host.command_stop = request.form.get('command_stop')
        host.command_restart = request.form.get('command_restart')
        host.server_name = request.form.get('server_name')
        host.server_type = request.form.get('server_type')
        host.server = request.form.get('server')
        host.users = [current_user]
        host.ssh_port = request.form.get('ssh_port')
        host.key = form.security_key.data
        if form.submit.data:
            if method == 'PUT':
                host.id = host_id
                if request.form.get('security') == '1':
                    host.key = None
                else:
                    host.password = None
                logger.info('execute update operation type <%s> primary key <%s>', logger_type, host_id)
                if HostService().update_one(host):
                    return redirect(url_for('host_view.index'))
            elif request.method == 'POST':
                if HostService().add(host):
                    return redirect(url_for('host_view.index'))
        if form.test_connection.data:
            ssh_connect = Ssh(hostname=host.hostname, port=host.ssh_port, username=host.username,
                              password=host.password,
                              private_key=host.key)
            if ssh_connect.check_connect() is False:
                flash('用户 <{}> 连接主机 <{}> 失败，错误如下：\r\n{}'.format(host.hostname, host.username, ssh_connect.get_message()))
            else:
                flash('用户 <{}> 连接主机 <{}> 成功！'.format(host.hostname, host.username))
                if StringUtils().is_not_empty(method):
                    return redirect(url_for('host_view.create_modfiy_copy_delete', host_id=host_id, method=method))
                else:
                    return redirect(url_for('host_view.create_modfiy_copy_delete', host_id=host_id))
    return render_template('host/host.html', form=form, host=host, title=title, active_menu='host')


@host_view.route('/delete/<int:host_id>', methods=['GET'])
@login_required
def delete(host_id=int):
    HostService().delete_one(host_id)
    return redirect(url_for('host_view.index', active_menu='host'))


@host_view.route('/info/<int:host_id>', methods=['GET'])
def info(host_id=int):
    host = HostService().find_one(id=host_id)
    return render_template('host/host-info.html', title='基本信息', active_menu='info', host=host, host_id=host_id)


@host_view.route('/connection/<int:host_id>', methods=['GET'])
def connection(host_id=int):
    connections = HostConnectionService().find_all_by_host_create_time_desc(host_id=host_id)
    return render_template('host/host-connection.html', title='连接历史', active_menu='connection', host_id=host_id,
                           connections=connections)


@host_view.route('/command/<int:host_id>', methods=['GET'])
@login_required
def command(host_id=int):
    commands = CommandExecuteService().find_all_by_host_create_time_desc(host_id=host_id)
    return render_template('host/host-command.html', title='命令历史', active_menu='command', host_id=host_id,
                           commands=commands)

agent/src/main/python/views/view_terminal.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020-04-13 18:27:03
# @Desc    : Web Terminal脚本
# @File    : view_terminal.py
from flask import render_template, Blueprint, redirect, url_for
from flask_login import current_user
from flask_login import login_required
from services.service_host import HostService

terminal_view = Blueprint('terminal_view', __name__, template_folder='templates')


@terminal_view.route('/open/<int:host_id>', methods=['GET'])
@login_required
def index(host_id=int):
    host = HostService().find_one(host_id)
    if host_id is None or host is None:
        return redirect(url_for('host_view.list'))
    count = HostService().count_by_user()
    return render_template('terminal/terminal.html', title='{}-终端'.format(host.hostname), server_id=host_id,
                           user=current_user)

agent/src/main/python/templates/host/base.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %} {{title}} {% endblock %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
{% endblock %}

{% block page_content %}
<div class="row">

    {% block alert %} {% endblock %}

    <div class="col-lg-2 col-12 side-main offset">
        {% block settings_left_menu %}
        <div class="panel panel-default">
            <div class="panel-heading">主机信息</div>
            <div class="panel-body" style="padding: 0px;">
                <div class="list-group" style="margin-bottom: 0px;">
                    <a href="{{ url_for('host_view.info', host_id=host_id) }}"
                       class="list-group-item {% if active_menu == 'info' %} active {% endif %}">基本信息</a>
                    <a href="{{ url_for('host_view.connection', host_id=host_id) }}"
                       class="list-group-item {% if active_menu == 'connection' %} active {% endif %}">连接历史</a>
                    <a href="{{ url_for('host_view.command', host_id=host_id) }}"
                       class="list-group-item {% if active_menu == 'command' %} active {% endif %}">命令历史</a>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>

    <div class="col-lg-10 col-12 conternt-main">
        {% block settings_right_content %} {% endblock %}
    </div>

</div>
{% endblock %}

agent/src/main/python/templates/host/host-command.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "host/base.html" %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
<script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
{% endblock %}

{% block alert %}
{% for message in get_flashed_messages() %}
<div class="alert alert-{{alert_type}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

{% block settings_right_content %}
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">命令历史</div>
    <div class="panel-body">
        <div class="col-lg-12 col-12 conternt-main offset">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>主机名称</th>
                    <th>执行账号</th>
                    <th>执行命令</th>
                    <th>开始时间</th>
                    <th>结束时间</th>
                    <th>连接总时长(秒)</th>
                    <th>执行状态</th>
                </tr>
                </thead>
                <tbody>
                {% for command in commands %}
                <tr>
                    <th scope="row">{{ command.id }}</th>
                    <td>{{ command.hostname }}</td>
                    <td>{{ command.username }}</td>
                    <td>{{ command.command }}</td>
                    <td>{{ command.start_time }}</td>
                    <td>{{ command.end_time }}</td>
                    <td>{{ command.elapsed_time /1000/1000 }}</td>
                    {% if command.final_state %}
                    <td>执行成功</td>
                    {% else %}
                    <td class="danger">
                        <span data-toggle="tooltip" data-placement="top" title="{{ logging.reason }}">执行失败 <i
                                class="fas fa-exclamation-triangle"></i></span>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

agent/src/main/python/templates/host/host-connection.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "host/base.html" %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
<script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
{% endblock %}

{% block alert %}
{% for message in get_flashed_messages() %}
<div class="alert alert-{{alert_type}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

{% block settings_right_content %}
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">连接历史</div>
    <div class="panel-body">
        <div class="col-lg-12 col-12 conternt-main offset">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>连接名</th>
                    <th>主机名称</th>
                    <th>连接用户</th>
                    <th>开始时间</th>
                    <th>结束时间</th>
                    <th>连接总时长(秒)</th>
                    <th>连接方式</th>
                    <th>失败原因</th>
                </tr>
                </thead>
                <tbody>
                {% for connection in connections %}
                <tr>
                    <th scope="row">{{ connection.id }}</th>
                    <td>{{ connection.name }}</td>
                    <td>{{ connection.hostname }}</td>
                    <td>{{ connection.username }}</td>
                    <td>{{ connection.start_time }}</td>
                    <td>{{ connection.end_time }}</td>
                    <td>{{ connection.elapsed_time /1000/1000 }}</td>
                    <td>{{ connection.type }}</td>
                    <td>{{ connection.reason }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

agent/src/main/python/templates/host/host-info.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "host/base.html" %}

{% block page_styles %}
<script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
<script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
{% endblock %}

{% block alert %}
{% for message in get_flashed_messages() %}
<div class="alert alert-{{alert_type}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

{% block settings_right_content %}
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">基本信息</div>
    <div class="panel-body">
        <div class="col-lg-12 col-12 conternt-main offset">
            <div class="col-lg-6 col-12 conternt-main offset">
                <div class="col-lg-3 col-12 conternt-main offset">
                    主机名
                </div>
                <div class="col-lg-9 col-12 conternt-main offset">
                    {{host.hostname}}
                </div>
            </div>
            <div class="col-lg-6 col-12 conternt-main offset">
                <div class="col-lg-3 col-12 conternt-main offset">
                    端口
                </div>
                <div class="col-lg-9 col-12 conternt-main offset">
                    {{host.ssh_port}}
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-12 conternt-main offset" style="margin-top: 10px;">
            <div class="col-lg-6 col-12 conternt-main offset">
                <div class="col-lg-3 col-12 conternt-main offset">
                    用户名
                </div>
                <div class="col-lg-9 col-12 conternt-main offset">
                    {{host.username}}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default" style="margin-bottom: 0px; border: 0px;">
    <div class="panel-heading">监控图表</div>
    <div class="panel-body">
        <div class="col-lg-12 col-12 conternt-main offset">
            <div class="col-lg-6 col-12 conternt-main offset">
                <div id="memory_line" class="row" style="height: 300px;"></div>
                <script>
                    $(
                        function () {
                            var chart = echarts.init(document.getElementById('memory_line'), 'white', {renderer: 'canvas'});
                            $.ajax({
                                type: "GET",
                                url: "/data/chart/host/{{host_id}}/memory/rate",
                                dataType: 'json',
                                success: function (result) {
                                    chart.setOption(result);
                                }
                            });
                        }
                    )
                </script>
            </div>
            <div class="col-lg-6 col-12 conternt-main offset">
                <div id="cpu_line" class="row" style="height: 300px;"></div>
                <script>
                    $(
                        function () {
                            var chart = echarts.init(document.getElementById('cpu_line'), 'white', {renderer: 'canvas'});
                            $.ajax({
                                type: "GET",
                                url: "/data/chart/host/{{host_id}}/cpu/rate",
                                dataType: 'json',
                                success: function (result) {
                                    chart.setOption(result);
                                }
                            });
                        }
                    )
                </script>
            </div>
        </div>
    </div>
</div>
{% endblock %}

agent/src/main/python/templates/host/host-list.html
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}主机列表{% endblock %}

{% block page_content %}

<!-- 监控数据 -->
<div class="card mt10">
    <h5 class="card-header">
        <a href="/host/cmcd" class="btn btn-sm btn-primary right" type="button">添加主机</a>
    </h5>
    <div class="card-body">
        <table class="table">
            <thead>
            <tr>
                <th>编码</th>
                <th>主机名</th>
                <th>SSH端口</th>
                <th>用户名</th>
                <th>服务</th>
                <th>创建时间</th>
                <th>节点操作</th>
            </tr>
            </thead>
            <tbody>
            {% for host in hosts %}
            <tr>
                <td>{{host.id}}</td>
                <td>{{host.hostname}}</td>
                <td>{{host.ssh_port}}</td>
                <td>{{host.username}}</td>
                <td>{{host.server}}</td>
                <td>{{host.create_time}}</td>
                <td>
                    <a class="btn btn-link btn-xs btn-xs-custom"
                       href="{{ url_for('host_view.create_modfiy_copy_delete', host_id=host.id, method='PUT') }}"
                       data-toggle="tooltip" data-placement="top" title="修改主机"
                       style="text-decoration:none; color:Mediumslateblue;">
                        <span class="fa-stack">
                          <i class="fas fa-square fa-stack-2x"></i>
                          <i class="fas fa-edit fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                    <a class="btn btn-link btn-xs btn-xs-custom"
                       href="{{ url_for('host_view.create_modfiy_copy_delete', host_id=host.id, type='') }}"
                       data-toggle="tooltip" data-placement="top" title="复制主机"
                       style="text-decoration:none; color:Dodgerblue;">
                        <span class="fa-stack">
                          <i class="fas fa-square fa-stack-2x"></i>
                          <i class="fas fa-copy fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                    <a class="btn btn-link btn-xs btn-xs-custom"
                       href="{{ url_for('host_view.delete', host_id=host.id) }}" data-toggle="tooltip"
                       data-placement="top" title="删除主机" style="text-decoration:none; color:Tomato;">
                        <span class="fa-stack">
                          <i class="fas fa-square fa-stack-2x"></i>
                          <i class="fas fa-trash-alt fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                    <div class="btn-group" data-toggle="tooltip" data-placement="top" title="更多设置">
                        <a class="btn btn-link btn-xs btn-xs-custom" data-toggle="dropdown">
                            <span class="fa-stack">
                                <i class="fas fa-square fa-stack-2x"></i>
                                <i class="fas fa fa-cog fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ url_for('host_view.info', host_id=host.id) }}" target="_blank">
                                    <span class="fa-stack">
                                      <i class="fas fa-square fa-stack-2x"></i>
                                      <i class="fas fa fa-info fa-stack-1x fa-inverse"></i>
                                    </span> 详情
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('chart_view.report', host_id=host.id) }}" target="_blank"
                                   data-toggle="tooltip" data-placement="top" title="监控报表"
                                   style="text-decoration:none; color: #17a2b8;">
                                    <span class="fa-stack">
                                      <i class="fas fa-square fa-stack-2x"></i>
                                      <i class="fas fa fa-chart-line fa-stack-1x fa-inverse"></i>
                                    </span> 监控报表
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('terminal_view.index', host_id=host.id) }}" target="_blank"
                                   data-toggle="tooltip" data-placement="top"
                                   title="连接终端" style="text-decoration:none; color:black;">
                                    <span class="fa-stack">
                                      <i class="fas fa-square fa-stack-2x"></i>
                                      <i class="fas fa-terminal fa-stack-1x fa-inverse"></i>
                                    </span> 连接终端
                                </a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{#<p>{{ moment(current_time).format('LLL') }}</p>#}
{#<p>{{ moment(current_time).fromNow(refresh=True) }}</p>#}

{% endblock %}